CREATE TABLE IF NOT EXISTS public.bs_debt_instruments_deals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id bigint NOT NULL REFERENCES bs_debt_instruments(id),
  deal_id bigint NOT NULL REFERENCES deal(id)
);

ALTER TABLE public.bs_debt_instruments_deals ENABLE ROW LEVEL SECURITY; 