create table if not exists "public"."auth_clerk_orgs_members" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint,
    "clerk_id" text not null,
    "clerk_organization_fkey" bigint,
    "clerk_role" clerk_role default 'member'::clerk_role,
    "created_at" timestamp with time zone not null default now(),
    "clerk_organization_id" text not null
);

alter table "public"."auth_clerk_orgs_members" enable row level security;

alter table "public"."auth_clerk_orgs_members" add constraint "auth_clerk_orgs_members_pkey" primary key ("id");
alter table "public"."auth_clerk_orgs_members" add constraint "auth_clerk_orgs_members_user_id_fkey" foreign key ("user_id") references "public"."auth_user_profiles" ("id");
alter table "public"."auth_clerk_orgs_members" add constraint "auth_clerk_orgs_members_clerk_organization_fkey_fkey" foreign key ("clerk_organization_fkey") references "public"."auth_clerk_orgs" ("id"); 