create table if not exists "public"."auth_clerk_orgs" (
    "id" bigint generated by default as identity not null,
    "clerk_organization_id" text not null,
    "clerk_organization_name" text not null,
    "clerk_organization_slug" text not null,
    "created_by_clerk_id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now()
);

alter table "public"."auth_clerk_orgs" enable row level security;

alter table "public"."auth_clerk_orgs" add constraint "auth_clerk_orgs_pkey" primary key ("id");
create unique index "auth_clerk_orgs_clerk_organization_id_key" on public.auth_clerk_orgs (clerk_organization_id);
create unique index "auth_clerk_orgs_slug_key" on public.auth_clerk_orgs (clerk_organization_slug); 