create table if not exists "public"."bsi_transactions" (
    "id" bigint generated by default as identity not null,
    "investor_id" bigint,
    "transaction_amount" numeric(15,2),
    "transaction_date" timestamp with time zone not null default now(),
    "transaction_method" transaction_method,
    "transaction_status" transaction_status,
    "reference_number" text,
    "reference_type" transaction_reference_type,
    "notes" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "deal_id" bigint,
    "ledger_entry_type" ledger_entry_type not null default 'contribution'::ledger_entry_type,
    "instrument_id" bigint,
    "clerk_id" text,
    "clerk_organization_id" text,
    "contact_company_id" text
);

alter table "public"."bsi_transactions" enable row level security;

alter table "public"."bsi_transactions" add constraint "bsi_transactions_pkey" primary key ("id");
alter table "public"."bsi_transactions" add constraint "bsi_transactions_investor_id_fkey" foreign key ("investor_id") references "public"."contact" ("id");
alter table "public"."bsi_transactions" add constraint "bsi_transactions_deal_id_fkey" foreign key ("deal_id") references "public"."deal" ("id");
alter table "public"."bsi_transactions" add constraint "bsi_transactions_instrument_id_fkey" foreign key ("instrument_id") references "public"."bs_debt_instruments" ("id");
alter table "public"."bsi_transactions" add constraint "bsi_transactions_contact_company_id_fkey" foreign key ("contact_company_id") references "public"."company" ("co_id"); 