-- Table: public.appraisal
CREATE TABLE public.appraisal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraiser_id bigint NULL,
  co_amc bigint NULL,
  co_appraisal bigint NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  date_amc_vendor_accept date NULL,
  date_amc_vendor_assign date NULL,
  date_inspection_completed date NULL,
  date_inspection_scheduled date NULL,
  date_report_effective date NULL,
  date_report_expiration date NULL,
  date_report_ordered date NULL,
  date_report_received date NULL,
  deal_id bigint NULL,
  document_id bigint NULL,
  file_number text NULL,
  file_number_amc text NULL,
  order_status public.appraisal_order_status NULL,
  order_type public.appraisal_order_type NULL,
  property_id bigint NULL,
  updated_at timestamp with time zone NULL,
  value_conclusion_as_is numeric NULL,
  value_conclusion_as_repaired numeric NULL,
  value_conclusion_fair_market_rent numeric NULL
);

-- Add foreign key constraints
ALTER TABLE public.appraisal ADD CONSTRAINT appraisal_appraiser_id_fkey FOREIGN KEY (appraiser_id) REFERENCES public.contact (id);
ALTER TABLE public.appraisal ADD CONSTRAINT appraisal_co_amc_fkey FOREIGN KEY (co_amc) REFERENCES public.company (co_id);
ALTER TABLE public.appraisal ADD CONSTRAINT appraisal_co_appraisal_fkey FOREIGN KEY (co_appraisal) REFERENCES public.company (co_id);
ALTER TABLE public.appraisal ADD CONSTRAINT appraisal_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deal (id);
ALTER TABLE public.appraisal ADD CONSTRAINT appraisal_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_files (id);
ALTER TABLE public.appraisal ADD CONSTRAINT appraisal_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property (id); 