-- Table: public.user_clerk_orgs
CREATE TABLE public.user_clerk_orgs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_organization_id text NOT NULL,
  clerk_organization_name text NOT NULL,
  clerk_organization_slug text NOT NULL,
  created_by_clerk_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
); 