-- Table: public.user_clerk_orgs_members
CREATE TABLE public.user_clerk_orgs_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_id text NOT NULL,
  clerk_organization_id text NOT NULL,
  clerk_organization_fkey bigint NULL,
  clerk_role public.clerk_role NULL,
  user_id bigint NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
-- Add RLS policies here if any exist in the current schema 