-- Table: public.bs_debt_instruments
CREATE TABLE public.bs_debt_instruments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  instrument_type public.debt_instrument_type NOT NULL,
  name text NOT NULL,
  target_yield_pct numeric NULL
); 