create table public.bs_debt_instruments_deals (
  id bigint generated by default as identity not null,
  instrument_id bigint not null,
  deal_id bigint not null,
  constraint bs_debt_instruments_deals_pkey primary key (id),
  constraint bs_debt_instruments_deals_deal_id_fkey foreign KEY (deal_id) references deal (id),
  constraint bs_debt_instruments_deals_instrument_id_fkey foreign KEY (instrument_id) references bs_debt_instruments (id)
) TABLESPACE pg_default;