-- Table: public.bsi_transactions_references
CREATE TABLE public.bsi_transactions_references (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint NOT NULL,
  reference_type public.transaction_reference_type NOT NULL,
  reference_value text NOT NULL
); 