-- Table: public.bsi_transactions
CREATE TABLE public.bsi_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NULL DEFAULT now(),
  deal_id bigint NULL,
  instrument_id bigint NULL,
  investor_id bigint NULL,
  transaction_date date NOT NULL,
  transaction_amount numeric NULL,
  ledger_entry_type public.ledger_entry_type NOT NULL,
  transaction_method public.transaction_method NULL,
  transaction_status public.transaction_status NULL,
  reference_number text NULL,
  reference_type public.transaction_reference_type NULL,
  notes text NULL,
  clerk_id text NULL,
  clerk_organization_id text NULL,
  updated_at timestamp with time zone NULL,
  CONSTRAINT bsi_transactions_pkey PRIMARY KEY (id)
); 