-- Table: public.cba_requests
CREATE TABLE public.cba_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NULL,
  submitted_by bigint NOT NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone NULL,
  uw_prequal_result_background bigint NULL,
  uw_prequal_result_credit bigint NULL
); 