-- Table: public.company_contact
CREATE TABLE public.company_contact (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  co_id bigint NULL,
  contact_id bigint NULL,
  deal_id bigint NULL
); 