-- Table: public.company_roles_defined
CREATE TABLE public.company_roles_defined (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  co_role public.company_role NOT NULL,
  description text NULL,
  deal_id bigint NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
); 