-- Table: public.company_member
CREATE TABLE public.company_member (
  member_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_company_id bigint NULL,
  member_owning_company_id bigint NULL,
  member_borrower_id bigint NULL,
  member_name_first text NULL,
  member_name_last text NULL,
  member_title text NULL,
  member_type public.vesting_type NULL,
  member_ownership_percentage numeric NULL,
  member_is_guarantor public.yes_no NULL,
  member_created_at timestamp with time zone NULL DEFAULT now(),
  member_updated_at timestamp with time zone NULL
); 