-- Table: public.company_roles
CREATE TABLE public.company_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  co_id bigint NOT NULL,
  role_id bigint NOT NULL,
  deal_id bigint NULL
); 