-- Table: public.constants
CREATE TABLE public.constants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NULL,
  description text NULL,
  type public.constant_types NULL,
  numeric_value numeric NULL,
  text_value text NULL,
  yes_no_value public.yes_no NULL,
  active boolean NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
); 