-- Table: public.contact
CREATE TABLE public.contact (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name text NULL,
  last_name text NULL,
  email_address text NULL,
  cell_phone text NULL,
  home_phone text NULL,
  office_phone text NULL,
  portal_access boolean NULL DEFAULT false,
  company_id bigint NULL,
  contact_type public.contact_type NULL,
  profile_picture text NULL,
  created_at timestamp with time zone NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  name text GENERATED ALWAYS AS (((first_name || ' '::text) || last_name)) STORED NULL,
  contact_types public.contact_type[] NULL,
  middle_name text NULL,
  user_id bigint NULL,
  CONSTRAINT contact_pkey PRIMARY KEY (id),
  CONSTRAINT contact_company_id_fkey FOREIGN KEY (company_id) REFERENCES company (co_id),
  CONSTRAINT contact_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profile (id)
);
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON contact FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
ALTER TABLE public.contact ENABLE ROW LEVEL SECURITY;
-- Add RLS policies here as needed 