-- Table: public.countries
CREATE TABLE public.countries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NULL,
  local_name text NULL,
  iso2 text NOT NULL,
  iso3 text NULL,
  continent public.continents NULL
); 