-- Table: public.deal_property
CREATE TABLE public.deal_property (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NOT NULL,
  property_id bigint NOT NULL
);

alter table "public"."deal_property" add constraint "deal_property_deal_id_fkey" foreign key ("deal_id") references "public"."deal" ("id");
alter table "public"."deal_property" add constraint "deal_property_property_id_fkey" foreign key ("property_id") references "public"."property" ("id"); 