-- Table: public.deal_appraisals
CREATE TABLE public.deal_appraisals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NULL,
  appraisal_id bigint NULL,
  property_Id bigint NULL
); 