-- Table: public.deal_roles
CREATE TABLE public.deal_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NULL,
  contact_id bigint NULL,
  contact_types_id bigint NULL
); 