-- Table: public.document_files
CREATE TABLE public.document_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NULL,
  category public.document_category NULL,
  deal_id bigint NULL,
  borrower_id bigint NULL,
  entity_id bigint NULL,
  property_id bigint NULL,
  guarantor_id bigint NULL,
  status public.document_status NULL,
  file_type text NULL,
  file_size bigint NULL,
  file_path text NULL,
  file_url text NULL,
  uploaded_at timestamp with time zone NULL,
  uploaded_by text NULL,
  is_required boolean NULL,
  effective_date date NULL,
  expiration_date date NULL,
  private_notes text NULL,
  public_notes text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Add foreign key constraints
ALTER TABLE "public"."document_files" ADD CONSTRAINT "document_files_deal_id_fkey" FOREIGN KEY ("deal_id") REFERENCES "public"."deal" ("id");
ALTER TABLE "public"."document_files" ADD CONSTRAINT "document_files_borrower_id_fkey" FOREIGN KEY ("borrower_id") REFERENCES "public"."borrower" ("id");
ALTER TABLE "public"."document_files" ADD CONSTRAINT "document_files_entity_id_fkey" FOREIGN KEY ("entity_id") REFERENCES "public"."company" ("co_id");
ALTER TABLE "public"."document_files" ADD CONSTRAINT "document_files_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."property" ("id");
ALTER TABLE "public"."document_files" ADD CONSTRAINT "document_files_guarantor_id_fkey" FOREIGN KEY ("guarantor_id") REFERENCES "public"."guarantor" ("guarantor_id"); 