-- Table: public.document_files
CREATE TABLE public.document_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NULL,
  category public.document_category NULL,
  deal_id bigint NULL,
  borrower_id bigint NULL,
  entity_id bigint NULL,
  property_id bigint NULL,
  guarantor_id bigint NULL,
  status public.document_status NULL,
  file_type text NULL,
  file_size bigint NULL,
  file_path text NULL,
  file_url text NULL,
  uploaded_at timestamp with time zone NULL,
  uploaded_by text NULL,
  is_required boolean NULL,
  effective_date date NULL,
  expiration_date date NULL,
  private_notes text NULL,
  public_notes text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 