-- Table: public.fee
CREATE TABLE public.fee (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  fee_amount_bps numeric NOT NULL,
  program public.loan_program NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 