-- Table: public.loan_program_b
CREATE TABLE public.loan_program_b (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NULL,
  final_rate numeric NULL,
  loan_price numeric NULL,
  pitia numeric NULL,
  dscr numeric NULL,
  origination numeric NULL,
  pass boolean NULL,
  created_at timestamp with time zone NULL,
  updated_at timestamp with time zone NULL
); 