-- Table: public.loan_application
CREATE TABLE public.loan_application (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_deal_id bigint NULL,
  submission jsonb NULL,
  status text NULL,
  error_message text NULL,
  reprocess boolean NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 