-- Table: public.ltv_band
CREATE TABLE public.ltv_band (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  ltv_min numeric NOT NULL,
  ltv_max numeric NOT NULL,
  notes text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
); 