-- Table: public.max_ltv
CREATE TABLE public.max_ltv (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program public.loan_program NOT NULL,
  fico_min integer NULL,
  fico_max integer NULL,
  citizenship public.citizenship NULL,
  property_type public.property_type NULL,
  loan_amount_min numeric NOT NULL,
  loan_amount_max numeric NULL,
  purchase_ltv numeric NULL,
  delayed_purchase_ltv numeric NULL,
  refinance_rt_ltv numeric NULL,
  refinance_co_ltv numeric NULL,
  short_term_rental public.yes_no NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
); 