-- Table: public.milestones
CREATE TABLE public.milestones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NOT NULL,
  milestone_template_id bigint NULL,
  milestone_order integer NULL,
  status public.milestone_status NULL,
  date_reached date NULL,
  date_completed date NULL,
  date_email_sent date NULL,
  email_sent boolean NULL,
  email_subject text NULL,
  email_body text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
); 