-- Table: public.milestone_templates
CREATE TABLE public.milestone_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  milestone_name text NOT NULL,
  milestone_order integer NULL,
  status public.milestone_status NULL,
  email_template_subject text NULL,
  email_template_body text NULL,
  subject_property_state public.us_states NULL,
  vesting_type public.vesting_type NULL,
  types_applied_to text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 