-- Table: public.payroll_submission
CREATE TABLE public.payroll_submission (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NULL,
  income_bpc_pct numeric NULL,
  income_bpc_usd numeric NULL,
  income_bpc_received_yn boolean NULL,
  income_bpc_received_datetime timestamp with time zone NULL,
  income_lpc_pct numeric NULL,
  income_lpc_usd numeric NULL,
  income_lpc_promo_usd numeric NULL,
  income_lpc_trailing_pct numeric NULL,
  income_lpc_trailing_usd numeric NULL,
  income_lpc_trailing_yn boolean NULL,
  income_net_usd numeric NULL,
  comp_ae_formula_output_pct numeric NULL,
  comp_ae_formula_output_usd numeric NULL,
  comp_ae_final_usd numeric NULL,
  comp_lp_formula_output_pct numeric NULL,
  comp_lp_formula_output_usd numeric NULL,
  comp_lp_final_usd numeric NULL,
  expense_ace_corp_return_usd numeric NULL,
  expense_ace_corp_override_usd numeric NULL,
  expense_misc_ppcc_usd numeric NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL
);

-- Add foreign key constraint for deal_id
ALTER TABLE public.payroll_submission ADD CONSTRAINT payroll_submission_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deal (id); 