-- Table: public.select_uw_outcomes
CREATE TABLE public.select_uw_outcomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  description text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 