-- Table: public.tasks
CREATE TABLE public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NULL,
  milestone_id bigint NULL,
  task_name text NOT NULL,
  task_description text NULL,
  task_order integer NULL,
  assigned_to bigint NULL,
  status public.task_status NULL,
  date_reached date NULL,
  date_completed date NULL,
  due_date date NULL,
  days_until_due integer NULL,
  task_action text NULL,
  task_complete boolean NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 