-- Table: public.task_templates
CREATE TABLE public.task_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name text NOT NULL,
  task_description text NULL,
  task_order integer NULL,
  assigned_to bigint NULL,
  milestone_template_id bigint NULL,
  status public.task_status NULL,
  date_reached date NULL,
  date_completed date NULL,
  due_date date NULL,
  days_until_due integer NULL,
  types_applied_to text NULL,
  task_action text NULL,
  email_template_subject text NULL,
  email_template_body text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
); 